services:
  - type: web
    name: drf-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn library.wsgi"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "drf-api.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: drf-db
          property: connectionString

databases:
  - name: drf-db
