# Generated by Django 4.2 on 2025-02-26 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_remove_user_course_remove_user_roll_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lms.course",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="roll_no",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
